# This is a basic workflow to help you get started with Actions

name: Bench

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        packages: [ "vim", "mariadb", "postgresql-server" ]
        host:     [ "http://download.opensuse.org", "http://mirrorcache-us.opensuse.org" ]
    container:
      image: opensuse/tumbleweed
    steps:
      - name: Install dependencies
        run: zypper -n in m4 git-core make sudo
      - name: Clone environ
        run: git clone https://github.com/andrii-suse/environ
      - name: Install environ
        run: |
          cd environ
          sudo make install
      - uses: actions/checkout@v2
      - name: Download package
        run: |
          environ -l $PWD zy1
          ENVIRON_PM_OPENSUSE_HOST=${{ matrix.host }} zy1/install --download-only ${{ matrix.packages }}
      - name: Results
        run: tail zy1/*/.seconds_install
