# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    container: opensuse/tumbleweed
    steps:
      - name: Install dependencies
        run: zypper -n in m4 git-core make sudo
      - name: Clone environ
        run: git clone https://github.com/andrii-suse/environ
      - name: Install environ
        run: cd environ; sudo make install
      - uses: actions/checkout@v2
      - name: Test
        run:  for f in t/*.sh ; do bash -x $f && continue; echo FAIL $f; exit 1; done
